#!/usr/bin/env bash

# Define the command for eww
EWW_CMD="eww -c $HOME/.config/eww"

# Start the Eww daemon if it's not running
if ! pgrep -x "eww" > /dev/null; then
    ${EWW_CMD} daemon
    sleep 1
fi

# Refresh widgets by closing all and reopening them
${EWW_CMD} close-all
pkill -x eww
${EWW_CMD} open-many bar